openapi: 3.0.0
info:
  description: Experian Releases Fairness as a Service on Ascend Intelligence Services™ to
    its Customers Experian bias assessment tool uses advanced academic and
    applied research to detect, explain and mitigate potential biases early on
    in lenders AI risk models
  version: 1.0.0
  title: Experian Fairness as a Service (FaaS) API
  contact:
    email: anandakumaran.sellathurai@experian.com
tags:
  - name: FaaS v1
    description: APIs to initiate FaaS processing and retrieve report
paths:
  /api/faas/process:
    post:
      tags:
        - FaaS v1
      summary: Initiate FaaS process for the shared data.
      parameters:
        - name: requestid
          description: Unique reference id for the dataset shared. Contact Experian team to
            upload data and a requestid.
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/faasinput"
        description: faas input object with information about data shared and filters.
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/processResponse"
  /api/faas/report:
    get:
      tags:
        - FaaS v1
      summary: get FaaS report by requestid and serviceid
      parameters:
        - name: serviceid
          description: To specify the service for which report is required. Accepted values
            are threshold_correction, faas_report, normative_report,
            explainability
          in: query
          required: true
          schema:
            type: string
        - name: requestid
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 200 response
          headers:
            content-encoding:
              schema:
                type: string
          content:
            application/zip:
              schema:
                $ref: "#/components/schemas/outputResponse"
            application/json:
              schema:
                $ref: "#/components/schemas/outputResponse"
servers:
  - url: https://srvm9v706a.execute-api.ap-southeast-1.amazonaws.com/test
components:
  schemas:
    faasinput:
      type: object
      required:
        - N_DECISION_THRESHOLDS
        - POSTCODE_COL
        - PREDICTION_COL
        - ProtectedAttributeColumn
        - ProtectedAttributeName
        - SCORE_COL
        - SENSITIVE_COL
        - SERVICE_ID
        - TARGET_COL
        - feature_cols
        - metrics
        - privilegedFilter
        - privilegedValue
        - protected_attributes
        - unPrivilegedFilter
        - unPrivilegedValue
      properties:
        PREDICTION_COL:
          title: The PREDICTION_COL schema
          type: string
          description: The predicted 1/0 output.
          default: prediction
        N_DECISION_THRESHOLDS:
          title: The N_DECISION_THRESHOLDS schema
          type: string
          description: Number of splits on score for fairness evaluation.
          default: "100"
        SENSITIVE_COL:
          title: The SENSITIVE_COL schema
          type: string
          description: Same as the protected column.
          default: ""
        POSTCODE_COL:
          title: The POSTCODE_COL schema
          type: string
          description: Column name on which normative data is merged with the base data.
          default: Region_Code
        ProtectedAttributeColumn:
          title: The ProtectedAttributeColumn schema
          type: string
          description: The protected attribute on which fairness assessment is to be done.
          default: CODE_GENDER
        privilegedValue:
          title: The privilegedValue schema
          type: string
          description: Value assigned to the privileged group.
          default: "1"
        unPrivilegedValue:
          title: The unPrivilegedValue schema
          type: string
          description: Value assigned to the under-privileged group.
          default: "0"
        SCORE_COL:
          title: The SCORE_COL schema
          type: string
          description: Score column, can store the value generated by predict_proba
            function of the model object.
          default: prediction_prob
        TARGET_COL:
          title: The TARGET_COL schema
          type: string
          description: The actual target or Y values.
          default: target
        ProtectedAttributeName:
          title: The ProtectedAttributeName schema
          type: string
          description: Name assigned to the protected group.
          default: CODE_GENDER
        privilegedFilter:
          title: The privilegedFilter schema
          type: string
          description: An explanation about the purpose of this instance.
          default: ""
        unPrivilegedFilter:
          title: The unPrivilegedFilter schema
          type: string
          description: Logic to filter priviliged group members.
          default: ==1
        protected_attributes:
          title: The protected_attributes schema
          type: string
          description: Attribute to be used for running normative data assessment approach.
          default: "['NoReligion']"
        metrics:
          title: The metrics schema
          type: string
          description: Normative approach metrices.
          default: "['disparate_impact','equal_opportunity_difference']"
        SERVICE_ID:
          title: SERVICE_ID
          type: string
          description: Service ID to specify the required service. Accepted values are
            threshold_correction, faas_report, normative_report, explainability
          default: ""
    outputResponse:
      title: Output Response
      required:
        - URL
      type: object
      properties:
        requestid:
          title: The URL schema
          type: string
          description: URL to download the generated output for the specific request id
          default: ""
      additionalProperties: true
      description: Response schema
      default: {}
    processResponse:
      title: Process Response
      required:
        - requestid
      type: object
      properties:
        requestid:
          title: The requestid schema
          type: string
          description: Requestid - unique reference for the transaction
          default: ""
      additionalProperties: true
      description: Response schema
      default: {}